version: '3.8'

services:
  go-voting-bot:
    build:
      context: ../.  # Каталог проекта (где лежит go.mod, go.sum)
      dockerfile: ./build/Dockerfile  # Путь к Dockerfile
    restart: unless-stopped
    environment:
      - MATTERMOST_TOKEN=
      - MATTERMOST_URL=
      - TARANTOOL_HOST=
      - TARANTOOL_PORT=
      - TARANTOOL_USER=
      - TARANTOOL_PASSWORD=
    ports:
      - "8080:8080"

  tarantool:
    image: tarantool/tarantool:latest
    restart: unless-stopped
    volumes:
      - tarantool_data:/data
    ports:
      - "3301:3301"

volumes:
  tarantool_data:
